### PR TITLE
Save/modify an item's data, including taxonomy and properties

### PR DESCRIPTION
**Pull request by pavel-mironchik**

### CODE REVIEW

**Comment by pavel-mironchik** [comment]
You can start a review from the commit 18c8eb1 (`Allow to modify general taxonomy on the client side.`)

**Comment by alquist42** [comment]
[Item Admin Page](https://trello.com/c/13xFsNVp/14-item-admin-page)

**Comment by alquist42** [comment]
[Convert Item fields 'geo_lat' and 'geo_lng' to the DECIMAL type](https://trello.com/c/3qgpltEM/18-convert-item-fields-geolat-and-geolng-to-the-decimal-type)

**Comment by alquist42** [comment]
[Update Vuetify to v2.3.3](https://trello.com/c/uLguQU8E/17-update-vuetify-to-v233)

**Pull request merged**
